# See https://pre-commit.com for more information
default_language_version:
  # default language version for each language used in the repository
  python: python3.8.3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      # See https://pre-commit.com/hooks.html for more hooks
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [ "--django" ]
      - id: trailing-whitespace
    # isort is a tool that sorts imports.
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.10.0
    hooks:
      - id: pyupgrade
        args: [ "--py36-plus", "--py37-plus", "--py38-plus", "--py39-plus" ]
  - repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
      - id: isort
    # Black is the code-formatter for Python.
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
    # Bandit is a security linter that checks code and reports security issues.
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args: [ "-iii", "-ll" ]
#  - repo: https://gitlab.com/pycqa/flake8
#    rev: 3.8.4
#    hooks:
#      - id: flake8
#        additional_dependencies: [
#            "flake8-bugbear",
#            "flake8-comprehensions",
#            "flake8-mutable",
#            "flake8-print",
#            "flake8-simplify",
#        ]
#  - repo: https://github.com/pycqa/pylint
#    rev: "pylint-2.7.2"
#    hooks:
#      - id: pylint
#        exclude: "[a-zA-Z]*/(migrations)/(.)*"
#        args: [ "--load-plugins=pylint_django", "--django-settings-module=app.settings" ]
#        additional_dependencies: [
#            # pylint dependency
#            pylint_django,
#            # runtime dependencies
#            # ...
#        ]
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: 'v0.812'
#    hooks:
#      - id: mypy
#        exclude: "[a-zA-Z]*/(migrations)/(.)*"
#        additional_dependencies: [
#            # mypy dependencies
#            djangorestframework-stubs,
#            django-stubs,
#            # runtime dependencies
#            # ...
#        ]
