# Generated by Django 3.2.4 on 2021-06-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=30)),
                ('data', models.TextField()),
            ],
        ),
    ]
